main: me.vislavy.testimony.Testimony
name: Testimony
description: Authorization plugin
author: vislavy
version: 1.0-SNAPSHOT
api-version: 1.18

commands:
  testimony:
    description: "Main plugin command"
    usage: "/testimony [reload/delaccount]"

permissions:
  testimony.command.*:
    description: "Access to all Testimony commands."
    default: op
    children:
      testimony.command.reload: true
      testimony.command.delaccount: true

  testimony.command.reload:
    description: "Access to /testimony reload."
    default: op

  testimony.command.delaccount:
    description: "Access to /testimony delaccount."
    default: op